name: Keep Cloud Run Warm v2

on:
  schedule:
    - cron: "*/5 * * * *"  # Every 5 minutes (UTC)
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    env:
      CLOUD_RUN_URL: ${{ secrets.CLOUD_RUN_URL }}
    steps:
      - name: Log current time
        run: echo "🕒 Cron triggered at $(date -u)"

      - name: Add a small random delay
        run: sleep $((RANDOM % 10 + 5))

      - name: Ping Cloud Run and log response
        run: |
          echo "🌐 Pinging $CLOUD_RUN_URL/healthcheck"
          curl -w "Status: %{http_code}\nTime: %{time_total}s\n" -o /dev/null "$CLOUD_RUN_URL/healthcheck"
