name: Keep Cloud Run Warm

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    env:
      CLOUD_RUN_URL: ${{ secrets.CLOUD_RUN_URL }}
    steps:
      - name: Ping Cloud Run service
        run: |
          curl "$CLOUD_RUN_URL/healthcheck"
